[package]
name = "elysius-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.0-rc0"
glam = "0.20"
rand = "0.8.4"

[profile.dev]
opt-level = 1